In [2]:
import tensorflow as tf
import keras 
import numpy as np


2024-09-14 15:25:17.365996: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-14 15:25:17.381565: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-14 15:25:17.400636: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-14 15:25:17.406286: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-14 15:25:17.420968: I tensorflow/core/platform/cpu_feature_guar

In [3]:


image = tf.constant(np.random.rand(10, 10, 1),dtype=tf.float32)

I0000 00:00:1726314921.247485   35096 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1726314921.280436   35096 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1726314921.281887   35096 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1726314921.284817   35096 cuda_executor.cc:1015] successful NUMA node read from SysFS ha

In [4]:
image

<tf.Tensor: shape=(10, 10, 1), dtype=float32, numpy=
array([[[0.6178089 ],
        [0.744687  ],
        [0.3592881 ],
        [0.92254287],
        [0.29604468],
        [0.714971  ],
        [0.70979756],
        [0.8794669 ],
        [0.7563301 ],
        [0.1911573 ]],

       [[0.91191536],
        [0.361762  ],
        [0.02060768],
        [0.6047104 ],
        [0.5661424 ],
        [0.910745  ],
        [0.37919608],
        [0.50190115],
        [0.36339098],
        [0.92394984]],

       [[0.9057035 ],
        [0.08699086],
        [0.48285988],
        [0.30703688],
        [0.73358476],
        [0.07623732],
        [0.7036193 ],
        [0.04472437],
        [0.52212274],
        [0.29356423]],

       [[0.913479  ],
        [0.4560498 ],
        [0.22915709],
        [0.17314339],
        [0.38477278],
        [0.87385386],
        [0.1525888 ],
        [0.30835605],
        [0.19207318],
        [0.02308316]],

       [[0.28742367],
        [0.13585758],
        [0.3039

In [5]:
tf.print(tf.image.per_image_standardization(image))

[[[0.43643567]
  [0.876734674]
  [-0.46069631]
  ...
  [1.34445465]
  [0.917139]
  [-1.04415226]]

 [[1.45705891]
  [-0.452111274]
  [-1.6360023]
  ...
  [0.0342067778]
  [-0.44645825]
  [1.49882162]]

 [[1.43550217]
  [-1.40563607]
  [-0.0318712071]
  ...
  [-1.5523113]
  [0.104380772]
  [-0.688774586]]

 ...

 [[1.21878481]
  [0.169487938]
  [0.157165051]
  ...
  [-1.38842058]
  [-0.702169478]
  [1.01576591]]

 [[1.45889616]
  [0.136382699]
  [-0.8954615]
  ...
  [-1.23530674]
  [1.25522518]
  [1.57190812]]

 [[0.112890504]
  [0.419103682]
  [1.39943266]
  ...
  [-0.876946151]
  [1.69606698]
  [-0.023265088]]]


In [9]:
class StandardizationLayer(keras.layers.Layer):
    def call(self, inputs):
        mean = tf.reduce_mean(inputs, axis=[1, 2], keepdims=True)
        stddev = tf.math.reduce_std(inputs, axis=[1, 2], keepdims=True)
        return (inputs - mean) / (stddev + 1e-6)  # Avoid division by zero
    
class PerImageStandardizationLayer(keras.layers.Layer):
    def call(self, inputs):
        return tf.image.per_image_standardization(inputs)

In [10]:
# tf.print(keras.layers.Normalization(mean=0, variance=1)(image))
tf.print(PerImageStandardizationLayer()(image))
# tf.print(StandardizationLayer()(image))

[[[0.43643567]
  [0.876734674]
  [-0.46069631]
  ...
  [1.34445465]
  [0.917139]
  [-1.04415226]]

 [[1.45705891]
  [-0.452111274]
  [-1.6360023]
  ...
  [0.0342067778]
  [-0.44645825]
  [1.49882162]]

 [[1.43550217]
  [-1.40563607]
  [-0.0318712071]
  ...
  [-1.5523113]
  [0.104380772]
  [-0.688774586]]

 ...

 [[1.21878481]
  [0.169487938]
  [0.157165051]
  ...
  [-1.38842058]
  [-0.702169478]
  [1.01576591]]

 [[1.45889616]
  [0.136382699]
  [-0.8954615]
  ...
  [-1.23530674]
  [1.25522518]
  [1.57190812]]

 [[0.112890504]
  [0.419103682]
  [1.39943266]
  ...
  [-0.876946151]
  [1.69606698]
  [-0.023265088]]]
